<h1><?= $tytul ?></h1>

<div class="row">
    <div class="col-lg-4">
        <?= $this->form()->openTag($form) ?>
        <?php $form->get('id_autora')->setAttributes(['readonly' => 'readonly', 'disabled' => true]); ?>
        <?php foreach($form->getElements() as $element){
            $element->setAttributes(['readonly' => 'readonly', array('disabled' => false)]);
        } ?>
        <div class="form-group">
            <?= $this->formLabel($form->get('tytul')) ?>
            <?= $this->formText($form->get('tytul')) ?>
            <?= $this->formElementErrors($form->get('tytul'), ['class' => 'help-block']) ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('id_autora')) ?>
            <?= $this->formSelect($form->get('id_autora')) ?>
            <?= $this->formElementErrors($form->get('id_autora'), ['class' => 'help-block']) ?>
        </div>
        <div class="form-group">
           
            <?= $this->formSubmit($form->get('usun')) ?>
            
            <a href="/pi1/public/ksiazki"> cancel</a>
        </div>
        
        <?= $this->form()->closeTag($form) ?>
    </div>
</div>
