<h1><?= $tytul ?></h1>

<div class="row">
    <div class="col-lg-4">
        <?= $this->form()->openTag($form) ?>
        <?php foreach($form->getElements() as $element){
            $element->setAttributes(['readonly' => 'readonly', 'disabled' => false]);
        } ?>
        <div class="form-group">
            <?= $this->formText($form->get('imie')) ?>
            <?= $this->formText($form->get('nazwisko')) ?>
            <?= $this->formElementErrors($form->get('imie'), ['class' => 'help-block']) ?>
        </div>
        <div class="form-group">
           
            <?= $this->formSubmit($form->get('usun')) ?>
            
            <a href="/pi1/public/autorzy"> cancel</a>
        </div>
        <?= $this->form()->closeTag($form) ?>
    </div>
</div>
